agents:
  - name: CompanyAnalystAgent
    role: "Senior Company Analyst"
    goal: "Analyze the {company}, find the information to understand the company."
    backstory: |
      You're an expert in analyzing companies.
      Your task includes finding company goals, key areas, industry sector it belongs to, 
      and other important information to get a better understanding of {company}.

  - name: UseCaseAdvisorAgent
    role: "Senior AI/ML Use Case Specialist"
    goal: "Propose relevant use cases in a specific markdown format where the company can leverage GenAI, LLMs, and latest technologies in AI-ML"
    backstory: |
      You're a Senior AI/ML Use Case Specialist.
      You are expert in proposing the best use cases for the company by analyzing industry trends 
      and standards within the company's sector related to AI, ML, and automation
      and You are expert in proposed use cases in provided markdown format.

  - name: FeasibilityCheckerAgent
    role: "Feasibility Analysis Specialist"
    goal: "Evaluate and prepare a feasibility report for the proposed use cases, considering economic and technical aspects"
    backstory: |
      You're an expert in evaluating use cases and preparing feasibility reports.
      Your role involves assessing wheather the use case is possible by checking that it is currently in use by others competitors and whether the company is economically and technically 
      capable of adopting the proposed solutions.

  - name: ResourceAssetCollectionAgent
    role: "Senior Resource Allocation Specialist"
    goal: |
      Identify and collect relevant datasets, tools, and frameworks that align with the proposed use cases.
      Additionally, propose optional Generative AI solutions like document search, automated report generation,
      and AI-powered chat systems for internal or customer-facing purposes.
    backstory: |
      You are an expert in curating resource assets for AI/ML projects.
      Your job is to search for datasets on platforms like Kaggle, Hugging Face, and GitHub,
      and propose tools or frameworks that enhance the feasibility of implementing the use cases.
      You ensure that all proposed resources are actionable, practical, and accessible to the company.

tasks:
  - name: CompanyAnalysisTask
    description: |
      Here is the company name {company}.
      Here is the company website URL {company_url}.
      You have to search this company by its website URL and name and scrape all the information of this company.
      Get details like company goals, key areas, industry sector it belongs to, and other important information.
    expected_output: "All relevant information about {company} to understand it."

  - name: UseCaseAdvisorTask
    description: |
        Based on the company industry conducted, analyze industry trends and standards within the company sector related to AI, ML, and automation.
        Propose relevant use cases in a specif markdown format where the company can leverage GenAI, LLMs, and ML technologies 
        to improve their processes, enhance customer satisfaction, and boost operational efficiency. 
        Search for industry-specific use cases and how other competitors levarages AI-ML.
        Also look over the latest reports ,articles from industry specific sources such as  McKinsey, Deloitte,Nexocode,etc.
        Ensure to add clickable references through which certain use cases were suggested.
        Your output should be in the following markdown format : 
        ### GenAI & ML Use Cases for {company} : 
        - Start with a brief description of the company, including its industry, key offerings, and strategic goals.
        - Highlight why AI/ML adoption is beneficial for the company.

        ---
        #### Use Case 1: [Title of the Use Case]
        **Objective/Use Case:** Provide a one-line summary of the primary goal for this use case.
        **AI Application:** Describe the AI/ML technology applied to achieve the objective.
        **Cross-Functional Benefit:**\n\n
          - **[Area 1]:** Explain how this use case benefits a specific department or function.
          - **[Area 2]:** Highlight additional benefits for other areas of the business.

        #### Use Case 2: [Title of the Use Case]
        **Objective/Use Case:** Provide a one-line summary of the primary goal for this use case
        **AI Application:** Describe the AI/ML technology applied to achieve the objective.
        **Cross-Functional Benefit:**
            - **[Area 1]:** Explain how this use case benefits a specific department or function.
            - **[Area 2]:** Highlight additional benefits for other areas of the business.
          
        <continue with other usecases>
        ---
        #### References
        Include references for the suggested use cases, with clickable links in markdown format.
        1. [Reference Title 1](https://example.com)
        2. [Reference Title 2](https://example.com)
        <continue with other refrences>
    expected_output: |
      The output must be in the following structured markdown format:

      ### GenAI & ML Use Cases for {company} : 
      - Start with a brief description of the company, including its industry, key offerings, and strategic goals.
      - Highlight why AI/ML adoption is beneficial for the company.

      ---
      #### Use Case 1: [Title of the Use Case]
      **Objective/Use Case:** Provide a one-line summary of the primary goal for this use case.
      **AI Application:** Describe the AI/ML technology applied to achieve the objective.
      **Cross-Functional Benefit:**\n\n
        - **[Area 1]:** Explain how this use case benefits a specific department or function.
        - **[Area 2]:** Highlight additional benefits for other areas of the business.

      #### Use Case 2: [Title of the Use Case]
      **Objective/Use Case:** Provide a one-line summary of the primary goal for this use case
      **AI Application:** Describe the AI/ML technology applied to achieve the objective.
      **Cross-Functional Benefit:**
          - **[Area 1]:** Explain how this use case benefits a specific department or function.
          - **[Area 2]:** Highlight additional benefits for other areas of the business.
        
      <continue with other usecases>
      ---
      #### References
      Include references for the suggested use cases, with clickable links in markdown format.
      1. [Reference Title 1](https://example.com)
      2. [Reference Title 2](https://example.com)
      <continue with other refrences>

      Ensure the output should be strictly in above markdown format.

  - name: FeasibilityCheckerTask
    description: |
        Evaluate the proposed AI/ML use cases for technical feasibility, scalability, and alignment with the company existing infrastructure.
        Analyze economic viability, resource requirements, and potential challenges to ensure successful implementation.
        Provide detailed recommendations, including potential risks, dependencies, and strategies for mitigation.

    expected_output: |
      ## Feasibility Analysis for {company}

      ### Use Case 1: {Use Case Title}
      **Technical Feasibility:**
      - Evaluate if the company has the necessary technical infrastructure and expertise to implement the solution.
      - Highlight any technology or platform requirements.

      **Economic Viability:**
      - Assess the cost implications of implementation and maintenance.
      - Recommend strategies to optimize resource usage and reduce costs.

      **Operational Readiness:**
      - Check if the company workforce is ready to adopt and integrate the solution.
      - Propose training or upskilling needs, if applicable.

      **Risks and Mitigation:**
      - List potential risks, including technical, financial, or operational challenges.
      - Suggest mitigation strategies for each identified risk.

      ### Use Case 2: {Use Case Title}
      -(Repeat the above structure for additional use cases.)


      ### Summary
      Provide a high-level summary of the overall feasibility of the proposed use cases, prioritizing the ones with the highest potential impact and feasibility.


  - name: ResourceAssetCollectionTask
    description: |
        Collect datasets, tools, and frameworks that align with the proposed use cases. "
        Search platforms such as Kaggle, Hugging Face, and GitHub for relevant resources. "
        Propose Generative AI solutions such as document search, automated report generation,AI-powered chat systems,etc for customer support and internal operations."
    expected_output: |
      ## Resource Asset Collection for {Company Name}

      ### Use Case 1: {Use Case Title}

      **Relevant Datasets:**
        - 1. [Dataset Name](Dataset Link) - Brief description of the dataset's purpose and features.
        - 2. [Dataset Name](Dataset Link) - Brief description.

      **Relevant Tools and Frameworks:**
        - 1. [Tool/Framework Name](Tool Link) - Brief explanation of its relevance and features.
        - 2. [Tool/Framework Name](Tool Link) - Brief explanation.

      **GenAI Solutions:** 
        - Suggest some GenAI solution for the company to enhance customer support , security , and for other things.

      ### Summary of Resources
      - Highlight key datasets, tools, and frameworks with their direct relevance to the use cases.

      ### References
      - Include links or citations for the resources collected, ensuring they are clickable.
